#########################################################################
####                         公共基础配置                              ####
#########################################################################
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

logging:
  config: classpath:log4j2-spring.yml

#########################################################################
####                     mybatis plus 配置                            ####
#########################################################################
mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.hantotem.property.domain.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    db-config:
      select-strategy: not_empty
      field-strategy: 1
